/**
 * HandoffPage.tsx
 * Executive Handoff Document — BondCurrent Platform
 * Generated by Gemini 2.5 Flash · Mar 10, 2026
 */
import Navbar from "@/components/Navbar";
import {
  Database,
  Globe,
  Brain,
  Shield,
  Rocket,
  Activity,
  CheckCircle,
  AlertTriangle,
  Server,
  RefreshCw,
  Clock,
  FileText,
  BarChart3,
  Lock,
  Trash2,
  Zap,
  Code2,
  Layers,
  Terminal,
  ChevronRight,
} from "lucide-react";

/* ── Phase data ─────────────────────────────────────────────── */

const phases = [
  {
    id: "Phase 0",
    title: "Foundation",
    accentVar: "var(--bc-blue)",
    icon: Database,
    items: [
      "Drizzle ORM Schema — sources, bookings, bonds, bondEvents, alertSubscriptions",
      "Most Wanted CMS Adapter — Cheerio-based static HTML scraper",
      "tRPC API Layer — type-safe procedures: bookings.search, ai.normalizeQuery",
      "Frontend Design Tokens — dark theme, Syne + DM Mono typography",
    ],
  },
  {
    id: "Phase 1",
    title: "Core UI",
    accentVar: "var(--bc-cyan)",
    icon: Layers,
    items: [
      "Search Card Component — name / charge / ID mode toggle, voice input",
      "Result Card Component — bond status borders, custody badge, DM Mono data",
      "Alert Subscription Modal — email watch, magic link confirmation",
      "Cron Scheduler — 30-min scrape cycle, event detection, bond change logging",
    ],
  },
  {
    id: "Phase 2",
    title: "Expansion",
    accentVar: "var(--bc-amber)",
    icon: Globe,
    items: [
      "Zuercher Portal Playwright Adapter — headless Chromium, XHR interception",
      "CSV Data Export endpoint — streaming, field escaping, attachment headers",
      "Redis Rate Limiting — 10 exports/hour per user, fixed-window algorithm",
    ],
  },
  {
    id: "Phase 3",
    title: "Intelligence",
    accentVar: "var(--bc-green)",
    icon: Brain,
    items: [
      "LLM Query Normalizer — GPT-4o-mini, Structured Outputs, zod schema",
      "Voice Search — Web Speech API → tRPC normalizeQuery → SQL filters",
      "Data Retention Policy — 90-day archive, 1-year hard delete, daily cron",
    ],
  },
  {
    id: "Phase 4",
    title: "Scale & Monetization",
    accentVar: "#a78bfa",
    icon: Rocket,
    items: [
      "Subscription Tier Enforcement — tRPC middleware, 3 searches/day free tier",
      "Admin Scrape Health Dashboard — per-source status, manual trigger, DM Mono data",
      "Manus Hosting Deployment — unified Express server, env vars, build scripts",
    ],
  },
];

/* ── Tech stack ──────────────────────────────────────────────── */

const stack = [
  { category: "Frontend",    items: ["React", "Vite", "TypeScript", "Syne + DM Mono"],                color: "blue" },
  { category: "Backend",     items: ["Node.js", "Express.js", "tRPC"],                                color: "blue" },
  { category: "Database",    items: ["MySQL / TiDB", "Drizzle ORM"],                                  color: "amber" },
  { category: "Caching",     items: ["Redis", "ioredis"],                                             color: "green" },
  { category: "Scraping",    items: ["Cheerio (static)", "Playwright (SPA)", "axios"],                color: "cyan" },
  { category: "AI Layer",    items: ["OpenAI GPT-4o-mini", "Structured Outputs", "zod"],              color: "purple" },
  { category: "Auth",        items: ["Manus OAuth", "JWT"],                                           color: "blue" },
  { category: "Scheduling",  items: ["node-cron", "date-fns"],                                        color: "green" },
  { category: "Deployment",  items: ["Manus Hosting", "S3 Snapshots"],                               color: "cyan" },
];

const chipStyle: Record<string, React.CSSProperties> = {
  blue:   { background: "rgba(37,99,235,0.12)",   color: "#60a5fa",  border: "1px solid rgba(37,99,235,0.25)" },
  cyan:   { background: "var(--bc-cyan-dim)",      color: "var(--bc-cyan)", border: "1px solid var(--bc-cyan-border)" },
  amber:  { background: "var(--bc-amber-dim)",     color: "var(--bc-amber)", border: "1px solid rgba(245,158,11,0.25)" },
  green:  { background: "var(--bc-green-dim)",     color: "var(--bc-green)", border: "1px solid rgba(16,185,129,0.25)" },
  purple: { background: "rgba(167,139,250,0.12)",  color: "#a78bfa",  border: "1px solid rgba(167,139,250,0.25)" },
};

/* ── Architecture layers ─────────────────────────────────────── */

const archLayers = [
  { label: "Client",         icon: Globe,     boxes: [{ label: "React SPA (Vite)", accent: true }, { label: "Web Speech API", accent: false }] },
  { label: "Express Server", icon: Server,    boxes: [{ label: "tRPC Router", accent: true }, { label: "Manus OAuth MW", accent: false }, { label: "CSV Export API", accent: false }, { label: "Static Files", accent: false }] },
  { label: "Data Layer",     icon: Database,  boxes: [{ label: "MySQL / TiDB", accent: true }, { label: "Redis", accent: false }, { label: "S3 Snapshots", accent: false }] },
  { label: "Workers",        icon: Clock,     boxes: [{ label: "Scrape Scheduler (30m)", accent: false }, { label: "Retention Cron (2AM)", accent: false }, { label: "Playwright Adapter", accent: true }] },
  { label: "AI Layer",       icon: Brain,     boxes: [{ label: "GPT-4o-mini NLP", accent: true }, { label: "Structured Outputs", accent: false }] },
];

/* ── Compliance ──────────────────────────────────────────────── */

const complianceItems = [
  { icon: Trash2,    title: "Data Retention",    color: "var(--bc-red)",   desc: "90-day archive for released inmates. Hard delete after 1 year. Automated via daily cron." },
  { icon: Zap,       title: "Rate Limiting",     color: "var(--bc-amber)", desc: "Redis-backed limits: 10 CSV exports/hour per user, 3 searches/day on free tier." },
  { icon: Lock,      title: "Authentication",    color: "var(--bc-blue)",  desc: "Manus OAuth with HttpOnly, Secure, SameSite=None cookies. JWT for session tokens." },
  { icon: Shield,    title: "TLS / SSL",         color: "var(--bc-green)", desc: "Managed by Manus Hosting. Playwright configured with ignoreHTTPSErrors for legacy parish certs." },
  { icon: Globe,     title: "User Agent",        color: "var(--bc-cyan)",  desc: "All scrapers identify as BondCurrent/1.0 with a public contact URL per Section 11.2." },
  { icon: BarChart3, title: "Tier Enforcement",  color: "#a78bfa",         desc: "tRPC middleware enforces subscription limits. Professional/Enterprise bypass daily caps." },
];

/* ── Scraper health mock ─────────────────────────────────────── */

const scraperHealth = [
  { parish: "St. Mary",    type: "Most Wanted CMS",       status: "ok",    lastScrape: "10 mins ago", bookings: 241 },
  { parish: "Jefferson",   type: "Zuercher Playwright",   status: "ok",    lastScrape: "30 mins ago", bookings: 1105 },
  { parish: "Plaquemines", type: "LA VINE / Appriss",     status: "error", lastScrape: "1 hour ago",  bookings: 0 },
];

/* ── Deploy steps ────────────────────────────────────────────── */

const deploySteps = [
  { step: "01", label: "Provision Resources",  desc: "TiDB/MySQL instance, Redis cache, S3 bucket in Manus dashboard" },
  { step: "02", label: "Set Env Variables",    desc: "DATABASE_URL, JWT_SECRET, OPENAI_API_KEY, REDIS_URL, PLAYWRIGHT_HEADLESS=true" },
  { step: "03", label: "DB Migration",         desc: "Run drizzle-kit push:mysql to apply schema to production TiDB" },
  { step: "04", label: "Deploy",               desc: "npm run build → npm start. Manus executes build pipeline automatically" },
];

/* ── Component ───────────────────────────────────────────────── */

export default function HandoffPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bc-bg)", color: "var(--bc-text)" }}>
      <Navbar />

      {/* ── Hero ── */}
      <section style={{ borderBottom: "1px solid var(--bc-border)", position: "relative", overflow: "hidden" }}>
        {/* Blueprint grid */}
        <div style={{
          position: "absolute", inset: 0, opacity: 0.03,
          backgroundImage: "linear-gradient(var(--bc-text) 1px, transparent 1px), linear-gradient(90deg, var(--bc-text) 1px, transparent 1px)",
          backgroundSize: "40px 40px",
          pointerEvents: "none",
        }} />
        <div className="container" style={{ paddingTop: "5rem", paddingBottom: "5rem", position: "relative" }}>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem", marginBottom: "1.5rem" }}>
            <span className="bc-badge bc-badge-cyan">Blueprint Execution Complete</span>
            <span className="bc-badge" style={{ background: "var(--bc-surface2)", color: "var(--bc-text-2)", border: "1px solid var(--bc-border-strong)" }}>
              gemini-2.5-flash · Mar 2026
            </span>
          </div>
          <h1 style={{ fontFamily: "var(--font-display)", fontSize: "clamp(2.5rem, 6vw, 4.5rem)", fontWeight: 800, letterSpacing: "-0.03em", lineHeight: 1.05, marginBottom: "1.25rem" }}>
            BondCurrent<br />
            <span className="bc-gradient-text">Executive Handoff</span>
          </h1>
          <p style={{ color: "var(--bc-text-2)", fontSize: "1.1rem", maxWidth: "600px", lineHeight: 1.7, marginBottom: "2rem" }}>
            A Louisiana bail-bond search and alert platform — built end-to-end from the product blueprint
            across four phases, covering the full stack from database schema to Manus Hosting deployment.
          </p>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "0.5rem" }}>
            {["4 Phases", "TypeScript · Full-Stack", "React + Node.js + tRPC", "MySQL/TiDB · Redis", "Playwright · Cheerio", "Manus Hosting"].map(tag => (
              <span key={tag} style={{
                fontFamily: "var(--font-mono)", fontSize: "0.72rem", padding: "0.3rem 0.75rem",
                borderRadius: "var(--radius-sm)", background: "var(--bc-surface2)",
                border: "1px solid var(--bc-border-strong)", color: "var(--bc-text-2)",
              }}>{tag}</span>
            ))}
          </div>
        </div>
      </section>

      {/* ── Executive Summary ── */}
      <section className="container" style={{ paddingTop: "4rem", paddingBottom: "4rem" }}>
        <SectionHeader icon={FileText} label="Executive Summary" />
        <div style={{ maxWidth: "700px", color: "var(--bc-text-2)", lineHeight: 1.8, display: "flex", flexDirection: "column", gap: "1rem" }}>
          <p>
            BondCurrent is a cutting-edge Louisiana bail-bond search and alert platform designed to provide
            real-time tracking of inmate booking and bond information. It serves attorneys, bondsmen, and
            families by offering a centralized, up-to-date source of data, enabling rapid response to changes
            in bond status.
          </p>
          <p>
            The platform emphasizes data accuracy, compliance, and a seamless user experience across its
            web interface and API. The system was built end-to-end from a product blueprint, translating
            every specification into production-ready TypeScript code across the full stack.
          </p>
        </div>
      </section>

      {/* ── Phases ── */}
      <section className="container" style={{ paddingBottom: "4rem" }}>
        <SectionHeader icon={Layers} label="Project Phases & Key Deliverables" />
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: "1rem" }}>
          {phases.map(phase => {
            const Icon = phase.icon;
            return (
              <div key={phase.id} className="bc-card" style={{ padding: "1.25rem", position: "relative", overflow: "hidden" }}>
                <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: "2px", background: phase.accentVar }} />
                <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "1rem" }}>
                  <div style={{ width: "2.25rem", height: "2.25rem", borderRadius: "var(--radius-md)", background: `${phase.accentVar}22`, display: "flex", alignItems: "center", justifyContent: "center" }}>
                    <Icon size={16} style={{ color: phase.accentVar }} />
                  </div>
                  <div>
                    <div style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--bc-text-3)" }}>{phase.id}</div>
                    <div style={{ fontWeight: 600, fontSize: "0.95rem" }}>{phase.title}</div>
                  </div>
                </div>
                <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "0.6rem" }}>
                  {phase.items.map(item => (
                    <li key={item} style={{ display: "flex", alignItems: "flex-start", gap: "0.5rem", fontSize: "0.8rem", color: "var(--bc-text-2)", lineHeight: 1.5 }}>
                      <CheckCircle size={12} style={{ color: "var(--bc-green)", flexShrink: 0, marginTop: "0.2rem" }} />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            );
          })}
        </div>
      </section>

      {/* ── Tech Stack ── */}
      <section style={{ borderTop: "1px solid var(--bc-border)", background: "var(--bc-surface)", paddingTop: "4rem", paddingBottom: "4rem" }}>
        <div className="container">
          <SectionHeader icon={Code2} label="Technology Stack" />
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: "0.75rem" }}>
            {stack.map(row => (
              <div key={row.category} style={{ display: "flex", alignItems: "flex-start", gap: "0.75rem", padding: "0.875rem 1rem", background: "var(--bc-surface2)", border: "1px solid var(--bc-border-strong)", borderRadius: "var(--radius-md)" }}>
                <span style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--bc-text-3)", width: "5rem", flexShrink: 0, paddingTop: "0.15rem" }}>{row.category}</span>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "0.4rem" }}>
                  {row.items.map(item => (
                    <span key={item} style={{ fontFamily: "var(--font-mono)", fontSize: "0.7rem", padding: "0.15rem 0.5rem", borderRadius: "var(--radius-sm)", ...chipStyle[row.color] }}>{item}</span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── System Architecture ── */}
      <section className="container" style={{ paddingTop: "4rem", paddingBottom: "4rem" }}>
        <SectionHeader icon={Server} label="System Architecture" />
        <p style={{ color: "var(--bc-text-2)", marginBottom: "2rem", maxWidth: "600px", lineHeight: 1.7 }}>
          BondCurrent operates as a <strong style={{ color: "var(--bc-text)" }}>single Node.js process</strong>, leveraging Express.js to unify the API, static frontend, and background workers under one roof.
        </p>
        <div style={{ maxWidth: "640px", display: "flex", flexDirection: "column", gap: "2px" }}>
          {archLayers.map((layer, i) => {
            const Icon = layer.icon;
            return (
              <div key={layer.label}>
                <div style={{ display: "flex", alignItems: "center", gap: "1rem", padding: "0.75rem 1rem", background: "var(--bc-surface)", border: "1px solid var(--bc-border)", borderRadius: "var(--radius-md)" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", width: "9rem", flexShrink: 0 }}>
                    <Icon size={14} style={{ color: "var(--bc-text-3)" }} />
                    <span style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--bc-text-3)" }}>{layer.label}</span>
                  </div>
                  <div style={{ display: "flex", flexWrap: "wrap", gap: "0.4rem" }}>
                    {layer.boxes.map(box => (
                      <span key={box.label} style={{
                        fontFamily: "var(--font-mono)", fontSize: "0.7rem", padding: "0.15rem 0.5rem", borderRadius: "var(--radius-sm)",
                        ...(box.accent
                          ? { background: "rgba(37,99,235,0.15)", color: "#60a5fa", border: "1px solid rgba(37,99,235,0.3)" }
                          : { background: "var(--bc-surface2)", color: "var(--bc-text-2)", border: "1px solid var(--bc-border-strong)" }),
                      }}>{box.label}</span>
                    ))}
                  </div>
                </div>
                {i < archLayers.length - 1 && (
                  <div style={{ textAlign: "center", fontFamily: "var(--font-mono)", fontSize: "0.65rem", color: "var(--bc-text-3)", padding: "0.2rem 0" }}>↕ tRPC / ORM / cron</div>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* ── Admin Health Dashboard ── */}
      <section style={{ borderTop: "1px solid var(--bc-border)", background: "var(--bc-surface)", paddingTop: "4rem", paddingBottom: "4rem" }}>
        <div className="container">
          <SectionHeader icon={Activity} label="Admin Scrape Health Dashboard" />
          <p style={{ color: "var(--bc-text-2)", marginBottom: "1.5rem", maxWidth: "600px", lineHeight: 1.7 }}>
            Live monitoring surface for the BondCurrent team. Displays per-source health, error states, and allows manual scrape triggers (Section 8.5).
          </p>
          <div style={{ maxWidth: "640px", display: "flex", flexDirection: "column", gap: "0.5rem" }}>
            {scraperHealth.map(source => (
              <div key={source.parish} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "1rem 1.25rem", background: "var(--bc-surface2)", border: "1px solid var(--bc-border-strong)", borderRadius: "var(--radius-md)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "0.875rem" }}>
                  <div style={{ width: "2rem", height: "2rem", borderRadius: "var(--radius-sm)", background: "var(--bc-surface)", border: "1px solid var(--bc-border)", display: "flex", alignItems: "center", justifyContent: "center" }}>
                    <Server size={14} style={{ color: "var(--bc-text-3)" }} />
                  </div>
                  <div>
                    <div style={{ fontWeight: 600, fontSize: "0.9rem" }}>{source.parish}</div>
                    <div style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--bc-text-3)" }}>{source.type}</div>
                  </div>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: "1.5rem" }}>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", textTransform: "uppercase", color: "var(--bc-text-3)" }}>Last Scrape</div>
                    <div style={{ fontFamily: "var(--font-mono)", fontSize: "0.8rem", color: "var(--bc-text-2)" }}>{source.lastScrape}</div>
                  </div>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", textTransform: "uppercase", color: "var(--bc-text-3)" }}>Bookings</div>
                    <div style={{ fontFamily: "var(--font-mono)", fontSize: "0.8rem", color: "var(--bc-text-2)" }}>{source.bookings.toLocaleString()}</div>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: "0.35rem", fontFamily: "var(--font-mono)", fontSize: "0.75rem", fontWeight: 600 }}>
                    {source.status === "ok"
                      ? <><CheckCircle size={15} style={{ color: "var(--bc-green)" }} /><span style={{ color: "var(--bc-green)" }}>OK</span></>
                      : <><AlertTriangle size={15} style={{ color: "var(--bc-red)" }} /><span style={{ color: "var(--bc-red)" }}>ERROR</span></>
                    }
                  </div>
                  <button className="bc-btn-icon" title="Trigger manual scrape"><RefreshCw size={14} /></button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Compliance ── */}
      <section className="container" style={{ paddingTop: "4rem", paddingBottom: "4rem" }}>
        <SectionHeader icon={Shield} label="Compliance & Security" />
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: "0.75rem" }}>
          {complianceItems.map(item => {
            const Icon = item.icon;
            return (
              <div key={item.title} style={{ padding: "1rem 1.25rem", background: "var(--bc-surface)", border: "1px solid var(--bc-border)", borderRadius: "var(--radius-md)" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.5rem" }}>
                  <div style={{ width: "1.75rem", height: "1.75rem", borderRadius: "var(--radius-sm)", background: `${item.color}18`, display: "flex", alignItems: "center", justifyContent: "center" }}>
                    <Icon size={13} style={{ color: item.color }} />
                  </div>
                  <span style={{ fontWeight: 600, fontSize: "0.875rem" }}>{item.title}</span>
                </div>
                <p style={{ fontSize: "0.78rem", color: "var(--bc-text-2)", lineHeight: 1.6, margin: 0 }}>{item.desc}</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* ── Deployment ── */}
      <section style={{ borderTop: "1px solid var(--bc-border)", background: "var(--bc-surface)", paddingTop: "4rem", paddingBottom: "4rem" }}>
        <div className="container">
          <SectionHeader icon={Rocket} label="Deployment Architecture (Manus Hosting)" />
          <p style={{ color: "var(--bc-text-2)", marginBottom: "2rem", maxWidth: "600px", lineHeight: 1.7 }}>
            Designed for seamless deployment on <strong style={{ color: "var(--bc-text)" }}>Manus Hosting</strong> as a single containerized Node.js process.
          </p>
          {/* Build commands */}
          <div style={{ maxWidth: "520px", marginBottom: "2.5rem", display: "flex", flexDirection: "column", gap: "0.4rem" }}>
            {[
              { label: "Build",        cmd: "npm run build",          desc: "Vite client + tsc server" },
              { label: "Start",        cmd: "npm start",              desc: "node dist-server/index.js" },
              { label: "DB Migration", cmd: "drizzle-kit push:mysql", desc: "First deploy only" },
              { label: "Node",         cmd: ">=20.0.0",               desc: "Required engine" },
            ].map(row => (
              <div key={row.label} style={{ display: "flex", alignItems: "center", gap: "1rem", padding: "0.65rem 1rem", background: "var(--bc-surface2)", border: "1px solid var(--bc-border-strong)", borderRadius: "var(--radius-md)" }}>
                <span style={{ fontFamily: "var(--font-mono)", fontSize: "0.65rem", textTransform: "uppercase", letterSpacing: "0.1em", color: "var(--bc-text-3)", width: "5.5rem", flexShrink: 0 }}>{row.label}</span>
                <code style={{ fontFamily: "var(--font-mono)", fontSize: "0.82rem", color: "var(--bc-cyan)", flex: 1 }}>{row.cmd}</code>
                <span style={{ fontSize: "0.75rem", color: "var(--bc-text-3)" }}>{row.desc}</span>
              </div>
            ))}
          </div>
          {/* Steps */}
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: "0.75rem" }}>
            {deploySteps.map(step => (
              <div key={step.step} style={{ padding: "1.25rem", background: "var(--bc-surface2)", border: "1px solid var(--bc-border-strong)", borderRadius: "var(--radius-md)" }}>
                <div style={{ fontFamily: "var(--font-display)", fontSize: "2rem", fontWeight: 700, color: "rgba(37,99,235,0.25)", marginBottom: "0.5rem" }}>{step.step}</div>
                <div style={{ fontWeight: 600, fontSize: "0.875rem", marginBottom: "0.35rem" }}>{step.label}</div>
                <p style={{ fontSize: "0.75rem", color: "var(--bc-text-2)", lineHeight: 1.6, margin: 0 }}>{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Future Considerations ── */}
      <section className="container" style={{ paddingTop: "4rem", paddingBottom: "4rem" }}>
        <SectionHeader icon={Terminal} label="Future Considerations" />
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: "0.75rem" }}>
          {[
            { title: "Memory Leaks",       desc: "Playwright browser instances must be closed in finally blocks. Monitor production heap usage continuously." },
            { title: "TLS Certificates",   desc: "Some parish government sites use self-signed certs. Zuercher adapter handles this via ignoreHTTPSErrors." },
            { title: "Data Accuracy",      desc: "Continuous validation of scraper output against source data. Snapshot diffs for change detection." },
            { title: "Monetization",       desc: "Stripe integration for Professional/Enterprise tiers. API key generation for enterprise clients." },
          ].map(item => (
            <div key={item.title} style={{ padding: "1rem 1.25rem", background: "var(--bc-surface)", border: "1px solid var(--bc-border)", borderRadius: "var(--radius-md)" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "0.4rem", marginBottom: "0.4rem" }}>
                <ChevronRight size={13} style={{ color: "var(--bc-cyan)" }} />
                <span style={{ fontWeight: 600, fontSize: "0.875rem" }}>{item.title}</span>
              </div>
              <p style={{ fontSize: "0.78rem", color: "var(--bc-text-2)", lineHeight: 1.6, margin: 0 }}>{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Footer ── */}
      <footer style={{ borderTop: "1px solid var(--bc-border)", padding: "2rem 0", textAlign: "center" }}>
        <p style={{ fontFamily: "var(--font-mono)", fontSize: "0.72rem", color: "var(--bc-text-3)" }}>
          Generated by <span style={{ color: "var(--bc-cyan)" }}>Gemini 2.5 Flash</span> via BondCurrent Blueprint Executor ·{" "}
          <span style={{ color: "var(--bc-blue)" }}>Mar 10, 2026</span>
        </p>
      </footer>
    </div>
  );
}

/* ── Section header helper ───────────────────────────────────── */

function SectionHeader({ icon: Icon, label }: { icon: React.ComponentType<{ size?: number; style?: React.CSSProperties }>; label: string }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "2rem" }}>
      <div style={{ width: "2rem", height: "2rem", borderRadius: "var(--radius-md)", background: "rgba(37,99,235,0.15)", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <Icon size={15} style={{ color: "var(--bc-blue)" }} />
      </div>
      <h2 style={{ fontFamily: "var(--font-display)", fontSize: "1.25rem", fontWeight: 700, letterSpacing: "-0.02em", margin: 0 }}>{label}</h2>
    </div>
  );
}
